### ISSUE TITLE
uwsgi + openssl 1.1 + psycopg2 bug

### ISSUE THREAD

**Issue by fjcrabiffosse** [tiangolo/uwsgi-nginx-docker#23]
Hi!

I have been using your base image tiangolo/uwsgi-nginx:python3.6 for a long time with great results but recently I encountered the error described in the following link:
https://www.bountysource.com/issues/46820777-openssl-1-1-uwsgi-psycopg2-no-ciphers-error

Seems the ubuntu base image used is inheriting the same issue, I have no solution for the bug except changing to your Alpine base image where the problem doesn't occur. Just letting you know in case you know of a workaround or feel like downgrading the version of the affected packages until the issue is solved.

**Comment by tiangolo** [comment]
It seems like that issue is different from the case of this image, as this image is based on the official Python image, it doesn't change anything from that one. And that one is based on Debian, not Ubuntu.

If you already solved your problem, feel free to close this issue.

If you still have an issue, you can create an environment that I can replicate and see the error and maybe I can take a look.
