### ISSUE TITLE
Use python:2.7-stretch and python:3.5-stretch in Dockerfile

### ISSUE THREAD

**Issue by desaintmartin** [tiangolo/uwsgi-nginx-docker#25]
Upgrade from oldstable to stable.
By default, python-3.5 and python-2.7 Docker images use Jessie, which is oldstable.

Allows to have newer packages like supervisor (3.0 -> 3.3, fixing annoying bugs).

**Comment by tiangolo** [comment]
If you are using Python 3.6, it uses stretch. If you need to use Python 2.7 with stretch, I just triggered a build, because the latest official Python 2.7 uses stretch too. So, in an hour or so the latest version of this image with Python 2.7 would be based on stretch.

If you specifically need Python 3.5 in stretch, I don't see an easy way to do it, as there is no official python:3.5-stretch.

Before diving deeper, can you check if that solves your problem?

**Comment by tiangolo** [comment]
It was actually required to update all the Nginx installation. I just did that and the images are already built. If you can, please check and let me know if it worked.

**Comment by desaintmartin** [comment]
I think you need to install ca-certificates in order for HTTPS-based websites (namely: pypi.org!) to work.

Maybe it is intended, as I've seen several docker image purposely NOT providing it, and the sub-image has to install it.

**Comment by tiangolo** [comment]
I'm being able to install packages with `pip`, I just tested it with `pip install requests`.

Are you referring to something else?

**Comment by desaintmartin** [comment]
I had a problem while doing ```pip install nose``` which returned a certificate error with pypi.org. Installing this package solved the problem. I am actually surprised it worked for you without the certificates installed in the container.

**Comment by tiangolo** [comment]
This should be fixed by PR #29 by @jkatzhrs , please check if it works for you. The images are being built right now, they should be available in some minutes.

**Comment by desaintmartin** [comment]
Indeed, closing. Thanks!
