### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by aericson** [tiangolo/uwsgi-nginx-docker#85]
Having problems with ssl certificates on python3.7 image. Can be reproduced with:

```
~ docker run -it --rm tiangolo/uwsgi-nginx:python3.7 curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

worked fine with `tiangolo/uwsgi-nginx:python3.7-2020-05-07`

**Comment by mybr4inhurts** [comment]
Reinstalling the ca-certificate package will solve that problem. 
You can add `RUN apt update && apt install --reinstall ca-certificates` to your dockerfile or you could execute the apt commands in your running container.

An image update would be nice though.

**Comment by tiangolo** [comment]
Thanks for the discussion here, and thanks for the help @mybr4inhurts!

As the packages installation was recently updated, it might be solved now. If it's not, could you @aericson please create a minimal self-contained example that replicates the issue? I imagine it could be just a small but complete `Dockerfile`.

Otherwise, if your problem is solved, you can close this issue. :heavy_check_mark:

**Comment by aericson** [comment]
Works fine now, thanks!
