### ISSUE TITLE
How can we make tensorflow work with this docker image? 

### ISSUE THREAD

**Issue by neilmario70** [tiangolo/uwsgi-nginx-docker#90]
I am using tensorflow version 2 to make predictions on uploaded images, however the server just times out and fails to make a prediction. I have the below module for making predictions. I use the **predict_class**  function on the incoming files on **main.py** If I disable my prediction function, everything works fine. I have increased the time for response to make sure that the process is not getting killed using the below code in mysetting.conf. 

`uwsgi_read_timeout 120s;`

I do not have any issues when I run the flask development server by logging into the container and running it manually and I am not sure what the issue is. 

However when I use **meinheld-gunicorn-flask-docker** image, everything is working as expected out of the box. Is there something that I am missing or some configuration that needs to be updated on this image? Any guidance will be appreciated. 

**predict.py**
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess_input
from PIL import Image
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
import pickle
import numpy as np
import os


folder_path = os.path.dirname(os.path.abspath(__file__))
model_path = os.path.join(folder_path, 'Logistic_model_resnet.sav')
res_model_path = os.path.join(folder_path, 'resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5')
resnet_base_model = ResNet50(weights=res_model_path, include_top=False, pooling='max')
logistic_model = pickle.load(open(model_path, 'rb'))

def predict_class(img_path):
    img = load_img(img_path, target_size=(224, 224), color_mode='grayscale')
    img_data = img_to_array(img)
    img_data = np.repeat(img_data, repeats = 3, axis = -1)
    img_data = np.expand_dims(img_data, axis=0)
    img_data = resnet_preprocess_input(img_data)
    feature_vector = resnet_base_model.predict(img_data)[0]
    prediction_result = logistic_model.predict([feature_vector])[0]
    return prediction_result

```

**Comment by tiangolo** [comment]
Hey! You might be running into timeouts from Nginx or from uWSGI. If the Meinheld image works for you, isn't that better?

In any case, if you are running a TensorFlow model (or any other type of ML with a model that requires a lot of memory) you would probably be better off with a simple `Dockerfile` built from scratch instead of this (or any other) base image. And using, for example, only Gunicorn with a single worker process.

That way you can manually and carefully increase the number of containers from outside, probably with Kubernetes, Docker Compose, Docker Swarm, or something similar. That way you don't risk having too many processes that consume all the memory and cause problems for the others.

And if you have a single process per container, then all the extra logic from this one is just unnecessary complexity.
